
-- Project Euler Problem 2
--
-- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
--
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
--By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


-- Here is the whole Fib Sequence
fibs = 1 : 1 : zipWith (+) fibs (tail fibs)
-- Here, 'a' is a list comprehension of all the even elements of fibs less than four million
a = [x|x<- takeWhile (<4000000) (tail(fibs)), x`mod`2==0] 

solution = sum a

main = print solution

